---
title: "Assignment - Machine Learning (Classification))"
author: "Dr Mohd Azmi P-UD 0079/19"
date: '`r format(Sys.Date(), "%d %B, %Y")`'
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float:
      collapsed: false
    number_sections: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F)
options(qwraps2_markup = "markdown", knitr.kable.NA = '')
```

# Motivation

Predict which notification will get delayed.

# Environment

## Packages

```{r}
library(pacman) # package manager, elegant way to load packages
p_load(tidyverse, haven, DT, rpart, summarytools)
```

## Dataset & Data Exploration

```{r}
delnotids <- read_sav("classdsfin2.sav") %>% mutate_if(is.labelled, ~(as_factor(.)))
delnotids
#delnotids %>% select(-id) %>% datatable()
```

```{r}
set.seed(119)
sRow <- sample(nrow(delnotids), nrow(delnotids)*.7)

delnotids_train <- delnotids[sRow,]
delnotids_test <- delnotids[-sRow,]
```


# Analysis & Result

## Descriptive

```{r}
freq(delnotids)
```




## Machine Learning - Decision Tree

```{r}
delnoti_dtmod <- rpart(DelayCode ~ Disease + NotiReqCode + FaciCollapseCode + DxWeekdayRecode + CaseClassReCode + DxStatRecodeNoMissing + ACDPCDReCode + CaseRegisterCode + Region + QuarterCode,
                       data = delnotids_train,
                       method = "class",
                       parms = list(split = "information"))
plot(delnoti_dtmod)
text(delnoti_dtmod)
```


### Prediction


# Discussion


# Conclusion

# Reference


# Additional Info

```{r}

```




```{r}
sessionInfo()
```

