---
title: "Assignment - Machine Learning (Regression))"
author: "Dr Mohd Azmi P-UD 0079/19"
date: '`r format(Sys.Date(), "%d %B, %Y")`'
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float:
      collapsed: false
    number_sections: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F)
options(qwraps2_markup = "markdown", knitr.kable.NA = '')
```

https://www.analyticsvidhya.com/blog/2017/09/creating-visualizing-neural-network-in-r/ - to update dataset, usinng normalize/standardize value

# Motivation

choice
1. check previous research - outcome score

# Environment

## Packages

```{r}
library(pacman)
p_load(haven, tidyverse, knitr, broom, rpart, rpart.plot, Metrics, neuralnet)
set.seed(119)
```

# Analysis

## Linear Regression

```{r}
mlregds <- read_sav("mlregds.sav") %>% mutate_if(is.labelled, ~(as_factor(.)))
mlregds0 <- read_sav("mlregds.sav")

mlregds
```

```{r}
sRow <- sample(nrow(mlregds), nrow(mlregds)*.7)

train <- mlregds[sRow,]
test <- mlregds[-sRow,]
```

```{r}
lr <- lm(Total_DS ~ HospCode + Age + GenderCode + MaritalCode + EduCode + IncomeCode + ComorbidCode + DMCode + HPTCode + OtherCode + ClinicalCauseCode + Duration2Code + NormalEye + BestVA + BlindVA2, train)

summary(lr)
```

```{r}
rmse(test$Total_DS, predict(lr,test))
```

## Decisional Tree

```{r}
ds_dtmod <- rpart(Total_DS ~ HospCode + Age + GenderCode + MaritalCode + EduCode + IncomeCode + ComorbidCode + DMCode + HPTCode + OtherCode + ClinicalCauseCode + Duration2Code + NormalEye + BestVA + BlindVA2, data = train, method = "anova")
rpart.plot(ds_dtmod)
```
```{r}
rmse(test$Total_DS, predict(ds_dtmod,test))
```

```{r}
ggplot(test, aes(x= Total_DS, y = predict(ds_dtmod,test))) + geom_point() + geom_smooth()

ggplot(train, aes(resid(ds_dtmod))) + geom_histogram()
```

## Neural Network

```{r}
max <- apply(mlregds0, 2, max)
min <- apply(mlregds0, 2, min)
mlregds_scaled <- as.data.frame(scale(mlregds0, center = min, scale = max - min))

train0 <- mlregds_scaled[sRow,]
test0 <- mlregds_scaled[-sRow,]
```

```{r}
mlregnn <- neuralnet(Total_DS ~ HospCode + Age + GenderCode + MaritalCode + EduCode + IncomeCode + ComorbidCode + DMCode + HPTCode + OtherCode + ClinicalCauseCode + Duration2Code + NormalEye + BestVA + BlindVA2, data = train0, hidden = 3, linear.output = T)
plot(mlregnn)
```

```{r}
rmse(test0$Total_DS, predict(mlregnn,test0))

```



